name: Release

on:
  push:
    branches:
      - main

jobs:
  publish-releases:
    name: Publish Releases
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: volta-cli/action@v3
      with:
        registry-url: https://registry.npmjs.org
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    - name: Publish Releases
      uses: thefrontside/actions/synchronize-with-npm@v2
      with:
        INSTALL_SCRIPT: yarn install && yarn pack
      env:
        GITHUB_TOKEN: ${{ secrets.FRONTSIDEJACK_GITHUB_TOKEN }}
